### ISSUE TITLE
indexDocument - performance in IE11

### ISSUE THREAD

**Issue by wwarme** [treasure-data/redux-search#49] opened 2016-08-19 13:15 UTC
Hello! 

I'm using redux-search for a big chunk of data. In fact I'm operating the international classification of diseases (ICD 10) on client-side (ajax-loaded though). It contains about 13.000 terminal diagnosis. redux-search performs **superb** so far, yet IE11 stutters a bit while operating the search function on that classifiaction, but there is a (big...) performance issue with the initial indexing process. 

redux-search is indexing the data field initially with a web worker (?) which takes 10 seconds in Firefox and 12-13 in Chrome, whereas IE 11 takes **over. one. whole. Minute.** I understand that a 13k entries list is far from a daily scenario, but I would like to know, why IE11 takes so much time for it. Running a profiler on IE boils it down on a forEach which the profiler cannot identify clearly, but it points to indexDocument one hierarchy above. 

Do you have any ideas what could take IE so long on indexDocument? I'm combing through your code already but it would be nice to have some help on it. I'm using babel for transpilation.

**Comment by bvaughn** [comment] 2016-08-19 14:54
Hey @wwarme,

Good to hear that redux-search is generally working well for you. I'm sorry that IE11's giving you performance problems though. For what it's worth, that's likely not due to redux-search at all- but to the underlying search lib, [js-worker-search](https://github.com/bvaughn/js-worker-search), since that's the code that actually manages the search index in the web worker.

I'm guessing [this is `indexDocument` method you're referring to](https://github.com/bvaughn/js-worker-search/blob/master/src/util/SearchUtility.js#L24-L38).

Maybe it would be more helpful if we moved this discussion/profiling over to js-worker-search? (I also maintain that library.) It might simplify the profiling a bit since it would remove all of the redux-middleware-specific code from the loop.

**Comment by bvaughn** [comment] 2016-08-19 14:56
I'm going to close this issue because (unless I'm wrong) the IE bottleneck isn't occurring in redux-search. Please open an issue [here](https://github.com/bvaughn/js-worker-search/issues/new) along with any profiling info or steps reproducing and I'll try to help you with it. :)

**Closed by bvaughn** 2016-08-19 14:56 UTC

**Comment by wwarme** [comment] 2016-08-19 16:55
Thanks for the fast reply! Yes I already figured that out, its probably js-worker-search. See you there. :)
