### ISSUE TITLE
example project: ERROR in Cannot find module '../features'

### ISSUE THREAD

**Issue by cyberxndr** [treasure-data/redux-search#46] opened 2016-05-04 08:31 UTC
Hi! There is a small issue in example project. After the `npm install` && `npm start` execution **and opening localhost:3456**, the following webpack error appears:
```
ERROR in Cannot find module '../features'
 @ ./website/Application.css 4:14-148 13:2-17:4 14:20-154

ERROR in Cannot find module '../features'
 @ ./website/components/Card/CardWrapper.css 4:14-160 13:2-17:4 14:20-166

ERROR in Cannot find module '../features'
 @ ./website/components/Footer/Footer.css 4:14-155 13:2-17:4 14:20-161

ERROR in Cannot find module '../features'
 @ ./website/components/Card/Card.css 4:14-153 13:2-17:4 14:20-159

ERROR in Cannot find module '../features'
 @ ./website/components/Header/Header.css 4:14-155 13:2-17:4 14:20-161

ERROR in Cannot find module '../features'
 @ ./website/components/Widget/Widget.css 4:14-155 13:2-17:4 14:20-161
```

Seems like this is related to `cssnext` module. When I remove it from `loaders: ['style', 'css?modules&importLoaders=1', 'cssnext']` all works well. Did i missed something, or it's an untested behaviour? Thanks.

**Comment by bvaughn** [comment] 2016-08-10 21:14
Wow. I've overlooked this issue for a long time. Sorry about that! It wasn't intentional.

I can't reproduce this error, having just `npm i && npm start` to verify. The "example project" (I assume you're referring to the Github pages site?) works fine for me, no errors. Maybe this was a transient issue- something that went wrong with an NPM install or a dependency?

Anyway, going to close it for now since things seem to be working okay for me.

**Closed by bvaughn** 2016-08-10 21:14 UTC
